import React,{useState} from 'react';
import {Loader2,Plus} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import useStudioWorkspace from '@/components/studio/useStudioWorkspace';
import StudioToolbar from '@/components/studio/StudioToolbar';
import StudioProjectPanel from '@/components/studio/StudioProjectPanel';
import StudioEditor from '@/components/studio/StudioEditor';
import StudioCreateDialog from '@/components/studio/StudioCreateDialog';
import StudioInboxDialog from '@/components/studio/StudioInboxDialog';
import '@/components/studio/studio.css';
export default function WebsiteStudio() {
 const studio=useStudioWorkspace(),[projectsOpen,setProjectsOpen]=useState(false),[inboxOpen,setInboxOpen]=useState(false);
 return <div className="studio-surface min-h-screen"><StudioToolbar studio={studio} onProjects={()=>setProjectsOpen(true)} onInbox={()=>setInboxOpen(true)}/>{studio.error&&<div className="studio-alert" role="alert">{studio.error}</div>}{studio.notice&&<div className="studio-notice" role="status">{studio.notice}</div>}{studio.busy&&<div className="studio-notice flex items-center gap-2" role="status"><Loader2 size={16} className="animate-spin"/>{studio.busy}</div>}<div className="studio-layout"><aside className="studio-projects"><StudioProjectPanel studio={studio}/></aside><main className="min-w-0">{studio.loading?<div className="flex gap-3 items-center justify-center min-h-[60vh] text-muted-foreground"><Loader2 className="animate-spin" size={22}/>Opening website source…</div>:studio.source&&studio.active?<StudioEditor key={studio.active.id} studio={studio}/>:<div className="max-w-xl mx-auto px-6 py-20"><span className="xa-pill-badge">Website Studio</span><h2 className="font-heading text-3xl font-bold mt-5">Build it. Edit it. Publish it.</h2><p className="text-muted-foreground mt-4">Create a website from a template or an AI brief, then edit its text, images, links and colors on the canvas. Drafts stay separate from your live website.</p><button className="xa-btn-primary mt-6" onClick={()=>studio.setCreate(true)}><Plus size={16}/>Create a Website</button>{studio.active&&<button className="xa-btn-outline mt-3 ml-2" onClick={()=>studio.open(studio.active.id,true)}>Retry Opening</button>}</div>}</main></div><Sheet open={projectsOpen} onOpenChange={setProjectsOpen}><SheetContent side="left" className="studio-surface p-0"><SheetHeader className="p-4"><SheetTitle>Studio Websites</SheetTitle><SheetDescription>Choose the website to edit.</SheetDescription></SheetHeader><StudioProjectPanel studio={studio} onClose={()=>setProjectsOpen(false)}/></SheetContent></Sheet><StudioCreateDialog studio={studio}/><StudioInboxDialog site={studio.active} open={inboxOpen} onOpenChange={setInboxOpen}/></div>;
}