import React,{useState} from 'react';
import {Loader2,Sparkles,ArrowRight} from 'lucide-react';
import StudioField from '@/components/studio/StudioField';
import {studioTemplates,buildTemplate} from '@/components/studio/studioTemplates';
import {studioCall} from '@/components/studio/useStudioWorkspace';
export default function StudioBuilder({onBuilt}) {
 const [name,setName]=useState(''),[brief,setBrief]=useState(''),[template,setTemplate]=useState('service'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const create=async ai=>{setBusy(ai?'Generating website…':'Creating draft…');setError('');try{const data=ai?await studioCall('runWebsiteBuilder',{business_name:name,niche:brief,style:template==='portfolio'?'editorial portfolio':template==='landing'?'focused modern landing page':'modern professional',draft_only:true}):await studioCall('studioWebsite',{operation:'create',title:name,brief,html:buildTemplate(template,name,brief)});onBuilt(data.build_id||data.site.id);}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy('');}};
 return <div className="space-y-5"><p className="text-sm text-muted-foreground">Start with a template or generate a custom design, then edit before publishing.</p><StudioField label="Website / business name" value={name} onChange={setName} maxLength={150} placeholder="Your business"/><StudioField label="What this website should say and do" value={brief} multiline onChange={setBrief} maxLength={4000} placeholder="Describe your services, audience and offer…"/><fieldset className="space-y-2"><legend className="font-semibold text-sm mb-2">Choose a starting layout</legend>{studioTemplates.map(item=><label key={item.id} className={`studio-template ${template===item.id?'studio-template-selected':''}`}><input type="radio" name="website-template" value={item.id} checked={template===item.id} onChange={()=>setTemplate(item.id)}/><span><strong className="block text-sm">{item.title}</strong><span className="text-xs text-muted-foreground">{item.description}</span></span></label>)}</fieldset><div className="flex gap-2 flex-wrap"><button className="xa-btn-primary" disabled={!!busy||!name.trim()||!brief.trim()} onClick={()=>create(false)}>{busy?<Loader2 size={16} className="animate-spin"/>:<ArrowRight size={16}/>}Open Template in Editor</button><button className="xa-btn-outline" disabled={!!busy||!name.trim()||!brief.trim()} onClick={()=>create(true)}><Sparkles size={16}/>Generate with AI</button></div>{busy&&<p role="status" className="text-sm text-muted-foreground">{busy}</p>}{error&&<p role="alert" className="studio-alert">{error}</p>}</div>;
}