import {useEffect,useRef,useState} from 'react';
import {base44} from '@/api/base44Client';
import {documentMetadata} from '@/components/studio/studioDocument';

export async function studioCall(name,payload) {const {data}=await base44.functions.invoke(name,payload);if(data.error)throw new Error(data.error);return data;}
const fields=['title','status','deployment_url','result','build_stage','last_error','studio_draft_uri','artifact_uri','draft_saved_at','published_at'];
export default function useStudioWorkspace() {
 const [projects,setProjects]=useState([]),[active,setActive]=useState(null),[source,setSource]=useState(''),[dirty,setDirty]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[create,setCreate]=useState(false),[cursor,setCursor]=useState(null),[search,setSearch]=useState('');
 const editor=useRef(null),loadId=useRef(0),savedHtml=useRef(''),draftHtml=useRef(''),activeId=useRef(null),alive=useRef(true);
 const refresh=async(more=false)=>{const query={build_type:'website',...(search.trim()?{title:{$regex:search.trim().replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'}}:{})};const page=await base44.entities.SystemBuild.filter(query,{sort:'-created_date',limit:30,fields,cursor:more?cursor:undefined});setProjects(v=>more?[...v,...page.items]:page.items);setCursor(page.has_more?page.next_cursor:null);return page.items;};
 const changed=html=>{draftHtml.current=html;setDirty(html!==savedHtml.current);};
 const open=async(id,force=false)=>{
  if(!force&&dirty&&!window.confirm('Discard your unsaved changes and open another website?'))return;
  const sequence=++loadId.current;setLoading(true);setError('');setNotice('');activeId.current=id;
  try{const data=await studioCall('studioWebsite',{operation:'load',build_id:id});if(sequence!==loadId.current)return;setActive(data.site);setSource(data.html);draftHtml.current=data.html;savedHtml.current=data.html;setDirty(false);}catch(e){if(sequence===loadId.current){setActive(projects.find(p=>p.id===id)||{id,title:'Website'});setSource('');setError(e.response?.data?.error||e.message);}}finally{if(sequence===loadId.current)setLoading(false);}
 };
 const save=async()=>{setBusy('Saving draft');setError('');try{const html=editor.current?.html()||draftHtml.current;const settings={...documentMetadata(html),target_keywords:active.target_keywords||'',competitors:active.competitors||''};const data=await studioCall('studioWebsite',{operation:'save',build_id:active.id,html,settings});savedHtml.current=html;draftHtml.current=html;setDirty(false);setActive(data.site);setNotice('Draft saved. Your live website has not changed.');await refresh();return {html,settings};}catch(e){setError(e.response?.data?.error||e.message);throw e;}finally{setBusy('');}};
 const publish=async()=>{setError('');setNotice('');setBusy('Publishing');try{const html=editor.current?.html()||draftHtml.current;const settings=documentMetadata(html);savedHtml.current=html;const saved=await studioCall('studioWebsite',{operation:'save',build_id:active.id,html,settings});setDirty(false);setActive(saved.site);let result=await studioCall('redeployWebsite',{build_id:active.id,html,settings});if(result.status==='deploying')setActive(v=>({...v,pending_deployment_id:result.deployment_id}));for(let i=0;result.status==='deploying'&&i<40&&alive.current;i++){setBusy('Publishing — waiting for Vercel');await new Promise(r=>setTimeout(r,3000));result=await studioCall('redeployWebsite',{operation:'status',build_id:active.id});}if(result.status==='deployed'){setActive(v=>({...v,status:'delivered',deployment_url:result.deploy_url,result:result.deploy_url,pending_deployment_id:''}));setNotice('Published. Your edited website is live.');}else setNotice('Vercel is still publishing. Use Check Publish to retrieve the result.');await refresh();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy('');}};
 const checkPublish=async()=>{setBusy('Checking publish');setError('');try{const result=await studioCall('redeployWebsite',{operation:'status',build_id:active.id});if(result.status==='deployed'){setActive(v=>({...v,status:'delivered',deployment_url:result.deploy_url,pending_deployment_id:''}));setNotice('Publication finished. Your website is live.');}else setNotice('Publication is still running.');await refresh();}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy('');}};
 useEffect(()=>{alive.current=true;let current=true;setLoading(true);refresh().then(items=>{if(current&&items[0])open(items[0].id,true);else if(current)setLoading(false);}).catch(e=>{if(current){setError(e.message);setLoading(false);}});return()=>{current=false;alive.current=false;};},[]);
 useEffect(()=>{const timer=setTimeout(()=>{refresh().catch(e=>setError(e.message));},250);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 return {projects,active,source,dirty,loading,busy,error,notice,create,setCreate,cursor,search,setSearch,editor,changed,open,save,publish,checkPublish,refresh,updateActive:data=>setActive(v=>({...v,...data}))};
}